version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyACM0
  adapter: zstack
  baudrate: 115200
  rtscts: false
frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: false
onboarding: false
